### ISSUE TITLE
Release checklist for 1.0.0

### ISSUE THREAD

**Issue by meain** [lsd-rs/lsd#750]
There are a few things that I wanted to track before the next release to make sure we don't miss that. Just adding them here so that I don't forget it as well there will be a public record of what is necessary for the next release.

If we only fix the required, we will release a minor version.

Required:
- https://github.com/lsd-rs/lsd/issues/865
- [x] https://github.com/Peltoche/lsd/issues/749: 
	- https://github.com/lsd-rs/lsd/pull/851
- [x] Quoting differences between gnu ls and lsd. https://github.com/Peltoche/lsd/pull/748
- [x] https://github.com/Peltoche/lsd/issues/780, linked PR https://github.com/lsd-rs/lsd/pull/792
- [x] https://github.com/lsd-rs/lsd/issues/828

If we can fix the optional in time, we will release a `1.0.0`, it is a milestone for us all

Optional:
- [x] https://github.com/lsd-rs/lsd/pull/822
- [x] https://github.com/lsd-rs/lsd/pull/830: *IMPORTANT* this update the icons with breaking change, dropped some obsolete icons, need noticeable release notes

**Comment by zwpaper** [comment]
Hi @meain, I was wondering how about we make this a `1.0.0` release, with the `colors`, icon theme, and git support.

at that time, lsd would be mostly a kinda feature completed, also recalling the email, it would also be great if we make the `1.0.0` moment happen to mark the progress we make previously.

**Comment by meain** [comment]
Yeah, that sounds like a great idea. That said, if things like git integration is taking time, we can probably release another minor version before that.

**Comment by zwpaper** [comment]
the good news is `git` has made some progress, and we may make it shortly hopefully🤣.

I also notice that we had not released a new version in a long time, but it also seems that the theme issues will not be fixed easily.

let me try to spend some more time to make the theme and git issues fixed.

**Comment by zwpaper** [comment]
as v1.0.0 could be an important release for us, I walk through the issue and decide that https://github.com/lsd-rs/lsd/issues/865 should be shipped within v1.0.0, let's wait some more while for the fix.

**Comment by zwpaper** [comment]
released https://github.com/lsd-rs/lsd/releases/tag/v1.0.0

/close
